name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@2a3661ac2b92d2da482640228e5202486550656f # main
