name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@aae195c19ec7069d2e91aca88107220ce807ef7e # main
