name: Stale issues & PRs

on:
  schedule:
    - cron: '0 5 * * *'  # daily
  workflow_dispatch:

jobs:
  stale:
    uses: chodeus/chodeus-ops/.github/workflows/stale-issues.yml@3f45de2e4563b8d1ec8e385d9b0cdc5508657ce8 # main
